// frontend/src/layouts/Layout.vue
<template>
  <v-app>
    <!-- 頂部導航列 -->
    <v-app-bar color="primary" elevation="2">
      <v-app-bar-nav-icon @click="drawer = !drawer" />
      <v-app-bar-title>
        <RouterLink to="/shop" class="text-white text-decoration-none">
          🛍️ 購物系統
        </RouterLink>
      </v-app-bar-title>

      <template v-slot:append>
        <!-- 聊天圖示 -->
        <v-btn icon @click="$router.push('/chat')">
          <v-badge :content="unreadCount > 0 ? unreadCount : ''" :model-value="unreadCount > 0" color="error">
            <v-icon>mdi-message</v-icon>
          </v-badge>
        </v-btn>

        <!-- 購物車圖示 -->
        <v-btn icon @click="$router.push('/cart')">
          <v-badge :content="cartCount > 0 ? cartCount : ''" :model-value="cartCount > 0" color="error">
            <v-icon>mdi-cart</v-icon>
          </v-badge>
        </v-btn>

        <!-- 使用者選單 -->
        <v-menu>
          <template v-slot:activator="{ props }">
            <v-btn icon v-bind="props">
              <v-avatar color="secondary" size="36">
                <span class="text-white text-body-2">{{ userInitial }}</span>
              </v-avatar>
            </v-btn>
          </template>
          <v-list>
            <v-list-item prepend-icon="mdi-account" title="個人資料" @click="$router.push('/profile')" />
            <v-list-item prepend-icon="mdi-heart" title="願望清單" @click="$router.push('/wishlist')" />
            <v-list-item prepend-icon="mdi-receipt" title="我的訂單" @click="$router.push('/orders')" />
            <v-list-item prepend-icon="mdi-key" title="Passkeys" @click="$router.push('/passkeys')" />
            <v-divider />
            <v-list-item
              v-if="user?.role === 'ADMIN'"
              prepend-icon="mdi-shield-account"
              title="管理後台"
              @click="$router.push('/admin')"
            />
            <v-divider v-if="user?.role === 'ADMIN'" />
            <v-list-item prepend-icon="mdi-logout" title="登出" @click="handleLogout" />
          </v-list>
        </v-menu>
      </template>
    </v-app-bar>

    <!-- 側邊導航抽屜 -->
    <v-navigation-drawer v-model="drawer" temporary>
      <v-list-item
        :title="user?.name || user?.username || '用戶'"
        :subtitle="user?.email"
        nav
      >
        <template v-slot:prepend>
          <v-avatar color="primary">
            <span class="text-white">{{ userInitial }}</span>
          </v-avatar>
        </template>
      </v-list-item>
      <v-divider />
      <v-list density="compact" nav>
        <v-list-item prepend-icon="mdi-store" title="商城" to="/shop" />
        <v-list-item prepend-icon="mdi-message" title="聊天" to="/chat">
          <template v-slot:append>
            <v-badge v-if="unreadCount > 0" :content="unreadCount" color="error" inline />
          </template>
        </v-list-item>
        <v-list-item prepend-icon="mdi-cart" title="購物車" to="/cart">
          <template v-slot:append>
            <v-badge v-if="cartCount > 0" :content="cartCount" color="error" inline />
          </template>
        </v-list-item>
        <v-list-item prepend-icon="mdi-receipt" title="我的訂單" to="/orders" />
        <v-list-item prepend-icon="mdi-heart" title="願望清單" to="/wishlist" />
        <v-list-item prepend-icon="mdi-account" title="個人資料" to="/profile" />
        <v-list-item prepend-icon="mdi-key" title="Passkeys" to="/passkeys" />
        <v-divider class="my-2" />
        <v-list-item
          v-if="user?.role === 'ADMIN'"
          prepend-icon="mdi-shield-account"
          title="管理後台"
          to="/admin"
        />
        <v-list-item prepend-icon="mdi-logout" title="登出" @click="handleLogout" />
      </v-list>
    </v-navigation-drawer>

    <!-- 主要內容 -->
    <v-main>
      <RouterView />
    </v-main>
  </v-app>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { RouterView, RouterLink, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/authStore.js'
import { cartAPI, chatAPI } from '../services/api.js'
import { cartEvents as cartEventsUtil } from '../utils/cartEvents.js'

const router = useRouter()
const authStore = useAuthStore()
const user = computed(() => authStore.user)
const userInitial = computed(() => {
  const name = user.value?.name || user.value?.username || '?'
  return name.charAt(0).toUpperCase()
})

const drawer = ref(false)
const cartCount = ref(0)
const unreadCount = ref(0)

async function loadCartCount() {
  if (!user.value?.id) return
  try {
    const response = await cartAPI.getCart(user.value.id)
    const cartData = response.data?.data || response.data
    cartCount.value = cartData?.items?.reduce((sum, item) => sum + (item.quantity || 0), 0) || 0
  } catch {}
}

async function loadUnreadCount() {
  if (!user.value?.id) return
  try {
    const response = await chatAPI.getUnreadCount(user.value.id)
    unreadCount.value = response.data?.unreadCount || response.data?.data?.unreadCount || 0
  } catch {}
}

function handleLogout() {
  authStore.logout()
  router.push('/login')
}

let interval = null

onMounted(() => {
  loadCartCount()
  loadUnreadCount()
  interval = setInterval(() => {
    loadCartCount()
    loadUnreadCount()
  }, 10000)

  cartEventsUtil.subscribe(() => loadCartCount())
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})
</script>

// frontend/src/components/Layout.jsx
import React, { useState, useEffect } from 'react';
import { Outlet } from 'react-router-dom';
import {
  AppBar,
  Toolbar,
  Typography,
  IconButton,
  Badge,
  Menu,
  MenuItem,
  Box,
  Container,
  Drawer,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  useTheme,
  useMediaQuery,
} from '@mui/material';
import {
  Menu as MenuIcon,
  ShoppingCart,
  AccountCircle,
  Store,
  FavoriteBorder,
  Receipt,
  Person,
  Logout,
  AdminPanelSettings,
  SmartToy,
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../stores/authStore';
import { cartAPI, chatAPI } from '../services/api';
import { cartEvents } from '../utils/cartEvents';

const Layout = () => {
  const navigate = useNavigate();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));

  const { user, logout } = useAuthStore();
  const [cartCount, setCartCount] = useState(0);

  const [anchorEl, setAnchorEl] = useState(null);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    loadCartCount();

    // 訂閱購物車變更事件
    const unsubscribe = cartEvents.subscribe(() => {
      loadCartCount();
    });

    // 每10秒更新一次購物車數量
    const interval = setInterval(loadCartCount, 10000);

    return () => {
      clearInterval(interval);
      unsubscribe();
    };
  }, [user?.id]);

  const loadCartCount = async () => {
    if (!user?.id) return;

    try {
      const response = await cartAPI.getCart(user.id);
      const cartData = response.data?.data || response.data;
      const count = cartData?.items?.reduce((sum, item) => sum + (item.quantity || 0), 0) || 0;
      setCartCount(count);
    } catch (error) {
      console.error('載入購物車數量失敗:', error);
    }
  };

  const handleMenu = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };

  const handleLogout = () => {
    logout();
    navigate('/login');
    handleClose();
  };

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };

  const menuItems = [
    { text: '商店', icon: <Store />, path: '/shop' },
    { text: 'AI助手', icon: <SmartToy />, path: '/ai' },
    { text: '購物車', icon: <ShoppingCart />, path: '/cart' },
    { text: '願望清單', icon: <FavoriteBorder />, path: '/wishlist' },
    { text: '訂單', icon: <Receipt />, path: '/orders' },
  ];

  const drawer = (
    <Box sx={{ width: 250 }}>
      <List>
        {menuItems.map((item) => (
          <ListItem
            key={item.text}
            component="button"
            onClick={() => {
              navigate(item.path);
              setMobileOpen(false);
            }}
            sx={{
              cursor: 'pointer',
              '&:hover': { bgcolor: 'action.hover' }
            }}
          >
            <ListItemIcon>{item.icon}</ListItemIcon>
            <ListItemText primary={item.text} />
          </ListItem>
        ))}
      </List>
    </Box>
  );

  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar position="fixed">
        <Toolbar>
          {isMobile && (
            <IconButton
              color="inherit"
              aria-label="open drawer"
              edge="start"
              onClick={handleDrawerToggle}
              sx={{ mr: 2 }}
            >
              <MenuIcon />
            </IconButton>
          )}

          <Typography
            variant="h6"
            component="div"
            sx={{ flexGrow: 1, cursor: 'pointer' }}
            onClick={() => navigate('/shop')}
          >
            現代電商平台
          </Typography>

          {!isMobile && (
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
              {menuItems.map((item) => (
                <IconButton
                  key={item.text}
                  color="inherit"
                  onClick={() => navigate(item.path)}
                  title={item.text}
                >
                  {item.text === '購物車' ? (
                    <Badge badgeContent={cartCount} color="secondary">
                      {item.icon}
                    </Badge>
                  ) : (
                    item.icon
                  )}
                </IconButton>
              ))}
            </Box>
          )}

          <IconButton
            size="large"
            aria-label="account of current user"
            aria-controls="menu-appbar"
            aria-haspopup="true"
            onClick={handleMenu}
            color="inherit"
          >
            <AccountCircle />
          </IconButton>

          <Menu
            id="menu-appbar"
            anchorEl={anchorEl}
            anchorOrigin={{
              vertical: 'top',
              horizontal: 'right',
            }}
            keepMounted
            transformOrigin={{
              vertical: 'top',
              horizontal: 'right',
            }}
            open={Boolean(anchorEl)}
            onClose={handleClose}
          >
            <MenuItem onClick={() => { navigate('/profile'); handleClose(); }}>
              <Person sx={{ mr: 1 }} />
              個人資料
            </MenuItem>

            {user?.role === 'ADMIN' && (
              <MenuItem onClick={() => { navigate('/admin'); handleClose(); }}>
                <AdminPanelSettings sx={{ mr: 1 }} />
                管理後台
              </MenuItem>
            )}

            <MenuItem onClick={handleLogout}>
              <Logout sx={{ mr: 1 }} />
              登出
            </MenuItem>
          </Menu>
        </Toolbar>
      </AppBar>

      {isMobile && (
        <Drawer
          variant="temporary"
          open={mobileOpen}
          onClose={handleDrawerToggle}
          ModalProps={{
            keepMounted: true,
          }}
        >
          {drawer}
        </Drawer>
      )}

      <Box
        component="main"
        sx={{
          flexGrow: 1,
          pt: 8,
          minHeight: '100vh',
          bgcolor: 'background.default',
        }}
      >
        <Container maxWidth="xl">
          <Outlet />
        </Container>
      </Box>
    </Box>
  );
};

export default Layout;
