// frontend/src/pages/Cart.vue
<template>
  <v-container class="py-6">
    <!-- 載入中 -->
    <div v-if="loading" class="d-flex justify-center py-12">
      <v-progress-circular indeterminate color="primary" size="48" />
    </div>

    <!-- 購物車空時 -->
    <div v-else-if="cartItems.length === 0" class="text-center py-12">
      <v-icon size="80" color="grey">mdi-cart-remove</v-icon>
      <h2 class="text-h5 mt-4 mb-2">購物車是空的</h2>
      <p class="text-medium-emphasis mb-6">快去挑選您喜歡的商品吧！</p>
      <v-btn color="primary" size="large" to="/shop" prepend-icon="mdi-store">繼續購物</v-btn>
    </div>

    <!-- 購物車內容 -->
    <template v-else>
      <h1 class="text-h4 font-weight-bold mb-6">購物車</h1>

      <v-row>
        <!-- 商品列表 -->
        <v-col cols="12" md="8">
          <v-card v-for="item in cartItems" :key="item.id" class="mb-4">
            <v-card-text>
              <v-row align="center">
                <!-- 商品圖片 -->
                <v-col cols="3" sm="2">
                  <v-img
                    v-if="item.product?.imageUrl"
                    :src="item.product.imageUrl"
                    :alt="item.productName || item.product?.name"
                    width="100"
                    height="100"
                    cover
                    rounded
                  />
                  <v-sheet
                    v-else
                    color="primary"
                    rounded
                    width="100"
                    height="100"
                    class="d-flex align-center justify-center"
                  >
                    <span class="text-white text-h6">
                      {{ (item.productName || item.product?.name || 'NA').substring(0, 2).toUpperCase() }}
                    </span>
                  </v-sheet>
                </v-col>

                <!-- 商品資訊 -->
                <v-col cols="9" sm="5">
                  <div class="text-body-1 font-weight-medium">
                    {{ item.productName || item.product?.name }}
                  </div>
                  <div v-if="item.product?.category" class="text-caption text-medium-emphasis">
                    分類: {{ item.product.category }}
                  </div>
                  <div class="text-body-1 font-weight-bold text-primary mt-1">
                    ${{ parseFloat(item.price || 0).toFixed(0) }}
                  </div>
                </v-col>

                <!-- 數量控制 -->
                <v-col cols="6" sm="3">
                  <div class="d-flex align-center justify-center ga-2">
                    <v-btn icon size="small" variant="outlined"
                      @click="handleQuantityChange(item.id, item.quantity - 1)"
                      :disabled="item.quantity <= 1">
                      <v-icon>mdi-minus</v-icon>
                    </v-btn>
                    <span class="text-body-1 font-weight-bold" style="min-width: 24px; text-align: center">
                      {{ item.quantity }}
                    </span>
                    <v-btn icon size="small" variant="outlined"
                      @click="handleQuantityChange(item.id, item.quantity + 1)">
                      <v-icon>mdi-plus</v-icon>
                    </v-btn>
                  </div>
                </v-col>

                <!-- 小計與刪除 -->
                <v-col cols="6" sm="2" class="text-center">
                  <div class="text-body-1 font-weight-semibold mb-2">
                    ${{ parseFloat(item.subtotal || (item.price * item.quantity) || 0).toFixed(0) }}
                  </div>
                  <v-btn icon size="small" color="error" variant="outlined"
                    @click="handleRemoveItem(item.id)">
                    <v-icon>mdi-delete</v-icon>
                  </v-btn>
                </v-col>
              </v-row>
            </v-card-text>
          </v-card>
        </v-col>

        <!-- 訂單摘要 -->
        <v-col cols="12" md="4">
          <v-card class="sticky-top" style="top: 80px">
            <v-card-title>訂單摘要</v-card-title>
            <v-card-text>
              <div v-for="item in cartItems" :key="item.id" class="d-flex justify-space-between mb-1 text-body-2">
                <span>{{ item.productName || item.product?.name }} x {{ item.quantity }}</span>
                <span>${{ parseFloat(item.subtotal || (item.price * item.quantity) || 0).toFixed(0) }}</span>
              </div>
              <v-divider class="my-3" />
              <div class="d-flex justify-space-between mb-1">
                <span>小計</span>
                <span>${{ parseFloat(cart?.total || 0).toFixed(0) }}</span>
              </div>
              <div class="d-flex justify-space-between mb-1">
                <span>運費</span>
                <span>$60</span>
              </div>
              <v-divider class="my-3" />
              <div class="d-flex justify-space-between text-body-1 font-weight-bold">
                <span>總計</span>
                <span class="text-primary">${{ (parseFloat(cart?.total || 0) + 60).toFixed(0) }}</span>
              </div>
            </v-card-text>
            <v-card-actions class="flex-column pa-4 ga-2">
              <v-btn color="primary" block size="large" prepend-icon="mdi-cart" @click="handleCheckout">
                結帳
              </v-btn>
              <v-btn color="error" variant="outlined" block @click="clearCartDialog = true">
                清空購物車
              </v-btn>
              <v-btn variant="text" block to="/shop">繼續購物</v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </template>

    <!-- 清空確認 Dialog -->
    <v-dialog v-model="clearCartDialog" max-width="360">
      <v-card>
        <v-card-title>清空購物車</v-card-title>
        <v-card-text>確定要清空購物車內的所有商品嗎？此操作無法復原。</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="clearCartDialog = false">取消</v-btn>
          <v-btn color="error" @click="handleClearCart">清空</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { cartAPI } from '../services/api.js'
import { useAuthStore } from '../stores/authStore.js'
import { cartEvents } from '../utils/cartEvents.js'

const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()
const user = computed(() => authStore.user)

const cart = ref(null)
const cartItems = ref([])
const loading = ref(true)
const clearCartDialog = ref(false)

async function loadCart() {
  if (!user.value?.id) return
  try {
    const response = await cartAPI.getCart(user.value.id)
    const cartData = response.data?.data || response.data
    cart.value = cartData
    cartItems.value = cartData?.items || []
    loading.value = false
  } catch {
    toast.error('載入購物車失敗')
    loading.value = false
  }
}

async function handleQuantityChange(itemId, newQuantity) {
  if (newQuantity < 1) { await handleRemoveItem(itemId); return }
  try {
    await cartAPI.updateCartItem(user.value.id, itemId, newQuantity)
    await loadCart()
    cartEvents.notify()
    toast.success('數量已更新')
  } catch (err) {
    toast.error(err.response?.data?.error || '更新失敗')
  }
}

async function handleRemoveItem(itemId) {
  try {
    await cartAPI.removeFromCart(user.value.id, itemId)
    await loadCart()
    cartEvents.notify()
    toast.success('已從購物車移除')
  } catch {
    toast.error('移除失敗')
  }
}

async function handleClearCart() {
  clearCartDialog.value = false
  try {
    await cartAPI.clearCart(user.value.id)
    await loadCart()
    cartEvents.notify()
    toast.success('購物車已清空')
  } catch {
    toast.error('清空購物車失敗')
  }
}

function handleCheckout() {
  if (cartItems.value.length === 0) { toast.error('購物車是空的！'); return }
  router.push('/checkout')
}

onMounted(() => {
  if (!user.value?.id) { router.push('/login'); return }
  loadCart()
})
</script>

// frontend/src/pages/Cart.jsx
﻿import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { cartAPI } from '../services/api';
import { useAuthStore } from '../stores/authStore';
import { cartEvents } from '../utils/cartEvents';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardTitle } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Plus, Minus, Trash2, ShoppingCart } from 'lucide-react';

export default function Cart() {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const [cart, setCart] = useState(null);
  const [cartItems, setCartItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openClearCartDialog, setOpenClearCartDialog] = useState(false);

  useEffect(() => {
    if (!user?.id) {
      navigate('/login');
      return;
    }
    loadCart();
  }, []);

  const loadCart = async () => {
    if (!user?.id) return;

    try {
      const response = await cartAPI.getCart(user.id);
      const cartData = response.data?.data || response.data;
      setCart(cartData);
      setCartItems(cartData?.items || []);
      setLoading(false);
    } catch (error) {
      console.error('載入購物車失敗:', error);
      toast.error('載入購物車失敗');
      setLoading(false);
    }
  };

  const handleQuantityChange = async (itemId, newQuantity) => {
    if (newQuantity < 1) {
      await handleRemoveItem(itemId);
      return;
    }

    try {
      await cartAPI.updateCartItem(user.id, itemId, newQuantity);
      await loadCart();
      cartEvents.notify();
      toast.success('數量已更新');
    } catch (error) {
      console.error('更新數量失敗:', error);
      toast.error(error.response?.data?.error || '更新失敗');
    }
  };

  const handleRemoveItem = async (itemId) => {
    try {
      await cartAPI.removeFromCart(user.id, itemId);
      await loadCart();
      cartEvents.notify();
      toast.success('已從購物車移除');
    } catch (error) {
      console.error('移除失敗:', error);
      toast.error('移除失敗');
    }
  };

  const handleClearCart = async () => {
    setOpenClearCartDialog(false);

    try {
      await cartAPI.clearCart(user.id);
      await loadCart();
      cartEvents.notify();
      toast.success('購物車已清空');
    } catch (error) {
      console.error('清空購物車失敗:', error);
      toast.error('清空購物車失敗');
    }
  };

  const handleCheckout = () => {
    if (cartItems.length === 0) {
      toast.error('購物車是空的!');
      return;
    }
    navigate('/checkout');
  };

  if (loading) {
    return (
      <div className='container mx-auto py-8 text-center'>
        <h2 className='text-xl font-medium'>載入中...</h2>
      </div>
    );
  }

  if (!cartItems || cartItems.length === 0) {
    return (
      <div className='container mx-auto py-8 text-center max-w-2xl'>
        <h1 className='text-3xl font-bold mb-4'>購物車是空的</h1>
        <p className='text-gray-500 mb-8'>
          快去挑選您喜歡的商品吧！
        </p>
        <Button
          size='lg'
          onClick={() => navigate('/shop')}
        >
          繼續購物
        </Button>
      </div>
    );
  }

  return (
    <div className='container mx-auto py-8 px-4'>
      <h1 className='text-3xl font-bold mb-8'>購物車</h1>

      <div className='flex flex-col md:flex-row gap-8'>
        {/* 購物車商品列表 */}
        <div className='flex-1'>
          {cartItems.map((item) => (
            <Card key={item.id} className='mb-4'>
              <CardContent className='p-4'>
                <div className='flex flex-col sm:flex-row gap-4 items-center'>
                  {/* 商品圖片 */}
                  <div className='w-[120px] h-[120px] flex-shrink-0 flex items-center justify-center bg-gray-100 rounded-md overflow-hidden'>
                    {item.product?.imageUrl ? (
                      <img
                        src={item.product.imageUrl}
                        alt={item.productName || item.product?.name}
                        className='object-contain w-full h-full'
                      />
                    ) : (
                      <div className='w-full h-full flex items-center justify-center bg-primary text-primary-foreground text-2xl font-bold'>
                        {(item.productName || item.product?.name || 'No').substring(0, 2).toUpperCase()}
                      </div>
                    )}
                  </div>

                  {/* 商品資訊 */}
                  <div className='flex-1 min-w-0 text-center sm:text-left'>
                    <h3 className='text-lg font-semibold mb-2'>
                      {item.productName || item.product?.name}
                    </h3>
                    {item.product?.category && (
                      <p className='text-sm text-gray-500'>
                        分類: {item.product.category}
                      </p>
                    )}
                    <p className='text-lg font-bold text-primary mt-2'>
                      ${parseFloat(item.price || 0).toFixed(0)}
                    </p>
                  </div>

                  {/* 數量控制 */}
                  <div className='flex items-center gap-2'>
                    <Button
                      variant='outline'
                      size='icon'
                      className='h-8 w-8'
                      onClick={() => handleQuantityChange(item.id, item.quantity - 1)}
                      disabled={item.quantity <= 1}
                    >
                      <Minus className='h-4 w-4' />
                    </Button>
                    <span className='w-8 text-center font-bold'>
                      {item.quantity}
                    </span>
                    <Button
                      variant='outline'
                      size='icon'
                      className='h-8 w-8'
                      onClick={() => handleQuantityChange(item.id, item.quantity + 1)}
                    >
                      <Plus className='h-4 w-4' />
                    </Button>
                  </div>

                  {/* 小計和刪除 */}
                  <div className='flex flex-col items-center min-w-[100px] gap-2'>
                    <p className='text-lg font-semibold'>
                      ${parseFloat(item.subtotal || (item.price * item.quantity) || 0).toFixed(0)}
                    </p>
                    <Button
                      variant='destructive'
                      size='icon'
                      className='h-8 w-8'
                      onClick={() => handleRemoveItem(item.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* 訂單摘要 */}
        <div className='md:w-1/3'>
          <Card className='sticky top-20'>
            <CardContent className='p-6'>
              <CardTitle className='mb-4 text-xl'>訂單摘要</CardTitle>

              <div className='space-y-2 mb-4'>
                {cartItems.map((item) => (
                  <div key={item.id} className='flex justify-between text-sm'>
                    <span>
                      {item.productName || item.product?.name} x {item.quantity}
                    </span>
                    <span>
                      ${parseFloat(item.subtotal || (item.price * item.quantity) || 0).toFixed(0)}
                    </span>
                  </div>
                ))}
              </div>

              <hr className='my-4 border-gray-200' />

              <div className='flex justify-between mb-2'>
                <span>小計</span>
                <span>
                  ${parseFloat(cart?.total || 0).toFixed(0)}
                </span>
              </div>

              <div className='flex justify-between mb-2'>
                <span>運費</span>
                <span>$60.00</span>
              </div>

              <hr className='my-4 border-gray-200' />

              <div className='flex justify-between mb-6 text-lg font-bold'>
                <span>總計</span>
                <span className='text-primary'>
                  ${(parseFloat(cart?.total || 0) + 60).toFixed(0)}
                </span>
              </div>

              <div className='space-y-3'>
                <Button
                  className='w-full'
                  size='lg'
                  onClick={handleCheckout}
                >
                  <ShoppingCart className='mr-2 h-4 w-4' /> 結帳
                </Button>

                <Button
                  variant='outline'
                  className='w-full text-red-500 hover:text-red-600 hover:bg-red-50 border-red-200 hover:border-red-300'
                  onClick={() => setOpenClearCartDialog(true)}
                >
                  清空購物車
                </Button>

                <Button
                  variant='ghost'
                  className='w-full'
                  onClick={() => navigate('/shop')}
                >
                  繼續購物
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* 清空購物車確認對話框 */}
      <Dialog open={openClearCartDialog} onOpenChange={setOpenClearCartDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>清空購物車</DialogTitle>
            <DialogDescription>
              確定要清空購物車內的所有商品嗎？此操作無法復原。
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant='outline'
              onClick={() => setOpenClearCartDialog(false)}
            >
              取消
            </Button>
            <Button
              variant='destructive'
              onClick={handleClearCart}
            >
              確定清空
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
