// frontend/src/pages/Chat.vue
<template>
  <div class="chat-wrapper" style="height: calc(100vh - 64px); display: flex; overflow: hidden">
    <!-- 聯絡人側邊欄 -->
    <div
      class="sidebar"
      :class="{ 'd-none': isMobile && selectedUser }"
      style="width: 280px; min-width: 280px; border-right: 1px solid rgba(0,0,0,0.12); overflow-y: auto; background: #fafafa"
    >
      <!-- 當前用戶資訊 -->
      <v-list-item
        :title="user?.name || user?.username || '用戶'"
        :subtitle="'@' + (user?.username || '')"
        class="pa-3"
      >
        <template v-slot:prepend>
          <v-avatar color="primary">
            <span class="text-white">{{ userInitial }}</span>
          </v-avatar>
        </template>
      </v-list-item>
      <v-divider />

      <!-- 聯絡人列表 -->
      <div class="pa-3">
        <p class="text-caption text-medium-emphasis mb-2">聯絡人</p>
      </div>
      <div v-if="users.length === 0" class="text-center pa-4 text-medium-emphasis text-body-2">
        沒有聯絡人
      </div>
      <v-list density="compact" nav v-else>
        <v-list-item
          v-for="contact in users"
          :key="contact.id"
          :active="selectedUser?.id === contact.id"
          color="primary"
          rounded
          class="mb-1"
          @click="handleSelectUser(contact)"
        >
          <template v-slot:prepend>
            <v-avatar color="secondary" size="36">
              <span class="text-white text-caption">
                {{ (contact?.name?.charAt(0) || contact?.username?.charAt(0) || '?').toUpperCase() }}
              </span>
            </v-avatar>
          </template>
          <template v-slot:title>
            <span class="text-body-2">{{ contact?.name || contact?.username || '未知用戶' }}</span>
          </template>
          <template v-slot:subtitle>
            <span class="text-caption">@{{ contact?.username || '' }}</span>
          </template>
          <template v-slot:append v-if="unreadCounts[contact.id] > 0">
            <v-badge :content="unreadCounts[contact.id]" color="error" />
          </template>
        </v-list-item>
      </v-list>
    </div>

    <!-- 聊天區域 -->
    <div class="flex-grow-1 d-flex flex-column" :class="{ 'd-none': isMobile && !selectedUser }">
      <!-- 聊天標題列 -->
      <div v-if="selectedUser" class="pa-3 d-flex align-center" style="border-bottom: 1px solid rgba(0,0,0,0.12)">
        <v-btn v-if="isMobile" icon size="small" variant="text" class="mr-2" @click="selectedUser = null">
          <v-icon>mdi-arrow-left</v-icon>
        </v-btn>
        <v-avatar color="secondary" size="36" class="mr-2">
          <span class="text-white text-caption">
            {{ (selectedUser?.name?.charAt(0) || selectedUser?.username?.charAt(0) || '?').toUpperCase() }}
          </span>
        </v-avatar>
        <div>
          <div class="text-body-1 font-weight-medium">{{ selectedUser?.name || selectedUser?.username }}</div>
          <div class="text-caption text-medium-emphasis">@{{ selectedUser?.username }}</div>
        </div>
      </div>

      <!-- 未選擇聯絡人 -->
      <div v-if="!selectedUser" class="d-flex align-center justify-center flex-grow-1 text-medium-emphasis">
        <div class="text-center">
          <v-icon size="64" color="grey">mdi-message-outline</v-icon>
          <p class="mt-2">請選擇聯絡人開始聊天</p>
        </div>
      </div>

      <!-- 訊息區域 -->
      <div
        v-else
        ref="messagesContainer"
        class="flex-grow-1 overflow-y-auto pa-4"
        style="background: #f5f5f5"
      >
        <div v-if="loading" class="d-flex justify-center pa-4">
          <v-progress-circular indeterminate color="primary" size="32" />
        </div>
        <div
          v-for="msg in messages"
          :key="msg.id"
          class="mb-3"
          :class="{ 'd-flex justify-end': msg.senderId === user?.id }"
        >
          <div
            class="pa-3 rounded-lg"
            style="max-width: 70%"
            :style="{
              background: msg.senderId === user?.id ? '#1976D2' : 'white',
              color: msg.senderId === user?.id ? 'white' : 'inherit',
              boxShadow: '0 1px 2px rgba(0,0,0,0.1)'
            }"
          >
            <div class="text-body-2">{{ msg.message || msg.content }}</div>
            <div class="d-flex align-center justify-end ga-1 mt-1 opacity-70" style="font-size: 11px">
              <span v-if="msg.senderId === user?.id && msg.isRead" class="text-caption">已讀</span>
              <span class="text-caption">{{ formatTime(msg.createdAt || msg.timestamp) }}</span>
            </div>
          </div>
        </div>
        <div ref="messagesEndRef" />
      </div>

      <!-- 輸入框 -->
      <div v-if="selectedUser" class="pa-3" style="border-top: 1px solid rgba(0,0,0,0.12)">
        <v-form @submit.prevent="handleSendMessage" class="d-flex ga-2">
          <v-text-field
            v-model="newMessage"
            placeholder="輸入訊息..."
            variant="outlined"
            density="compact"
            hide-details
            class="flex-grow-1"
            @keydown.enter.prevent="handleSendMessage"
          />
          <v-btn
            type="submit"
            color="primary"
            icon
            :disabled="!newMessage.trim()"
          >
            <v-icon>mdi-send</v-icon>
          </v-btn>
        </v-form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { useDisplay } from 'vuetify'
import { authAPI, chatAPI } from '../services/api.js'
import { useAuthStore } from '../stores/authStore.js'

const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()
const user = computed(() => authStore.user)
const userInitial = computed(() => {
  const name = user.value?.name || user.value?.username || '?'
  return name.charAt(0).toUpperCase()
})

const { smAndDown } = useDisplay()
const isMobile = computed(() => smAndDown.value)

const users = ref([])
const selectedUser = ref(null)
const messages = ref([])
const newMessage = ref('')
const loading = ref(false)
const unreadCounts = ref({})
const messagesEndRef = ref(null)
const messagesContainer = ref(null)

let mainInterval = null
let unreadInterval = null

function scrollToBottom() {
  nextTick(() => {
    messagesEndRef.value?.scrollIntoView({ behavior: 'smooth' })
  })
}

function formatTime(timestamp) {
  if (!timestamp) return ''
  return new Date(timestamp).toLocaleTimeString('zh-TW', { hour: '2-digit', minute: '2-digit' })
}

async function loadUsers() {
  try {
    const response = await authAPI.getUsers()
    const data = response.data?.data || response.data || []
    users.value = Array.isArray(data) ? data.filter(u => u.id !== user.value?.id) : []
  } catch {
    users.value = []
  }
}

async function loadUnreadCounts() {
  if (!user.value?.id) return
  try {
    const response = await chatAPI.getUnreadMessages(user.value.id)
    const msgs = response.data?.data || response.data || []
    const counts = {}
    if (Array.isArray(msgs)) {
      msgs.forEach(msg => {
        if (msg.senderId && msg.senderId !== user.value.id) {
          counts[msg.senderId] = (counts[msg.senderId] || 0) + 1
        }
      })
    }
    unreadCounts.value = counts
  } catch {}
}

async function loadMessages(showLoading = true) {
  if (!selectedUser.value) return
  if (showLoading) loading.value = true
  try {
    const response = await chatAPI.getChatHistory(user.value.id, selectedUser.value.id)
    messages.value = response.data?.data || response.data || []
    await chatAPI.markChatAsRead(user.value.id, selectedUser.value.id)
    // 標記已讀後重新載入，讓對方已讀狀態即時更新
    const response2 = await chatAPI.getChatHistory(user.value.id, selectedUser.value.id)
    messages.value = response2.data?.data || response2.data || []
    await loadUnreadCounts()
    scrollToBottom()
  } catch {}
  finally {
    if (showLoading) loading.value = false
  }
}

async function handleSelectUser(contact) {
  selectedUser.value = contact
  messages.value = []
  try {
    await chatAPI.markChatAsRead(user.value.id, contact.id)
    await loadUnreadCounts()
  } catch {}
}

async function handleSendMessage() {
  if (!newMessage.value.trim() || !selectedUser.value) return
  try {
    await chatAPI.sendMessage({
      senderId: user.value.id,
      receiverId: selectedUser.value.id,
      message: newMessage.value.trim(),
    })
    newMessage.value = ''
    await loadMessages(false)
  } catch {
    toast.error('發送失敗，請稍後再試')
  }
}

watch(selectedUser, (newUser) => {
  if (mainInterval) clearInterval(mainInterval)
  if (newUser) {
    loadMessages()
    mainInterval = setInterval(() => {
      loadMessages(false)
      loadUnreadCounts()
    }, 3000)
  }
})

onMounted(() => {
  loadUsers()
  loadUnreadCounts()
  unreadInterval = setInterval(loadUnreadCounts, 5000)
})

onUnmounted(() => {
  if (mainInterval) clearInterval(mainInterval)
  if (unreadInterval) clearInterval(unreadInterval)
})
</script>

// frontend/src/pages/Chat.jsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { authAPI, chatAPI } from '../services/api';
import { useAuthStore } from '../stores/authStore';
import '../styles/Chat.css';

function Chat() {
  const { user, logout } = useAuthStore();
  const navigate = useNavigate();
  const [users, setUsers] = useState([]);
  const [selectedUser, setSelectedUser] = useState(null);
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [unreadCounts, setUnreadCounts] = useState({}); // 每個用戶的未讀數量
  const [isMobile, setIsMobile] = useState(false); // 檢測是否為手機
  const messagesEndRef = useRef(null);
  const intervalRef = useRef(null);

  // 檢測螢幕大小
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth <= 768);
    };

    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  // 載入所有用戶
  useEffect(() => {
    loadUsers();
    loadUnreadCounts(); // 載入未讀數量

    // 即使沒有選擇用戶，也定期更新未讀數量
    const unreadInterval = setInterval(() => {
      loadUnreadCounts();
    }, 5000); // 每5秒更新一次

    return () => clearInterval(unreadInterval);
  }, []);

  // 自動刷新訊息和未讀數量
  useEffect(() => {
    if (selectedUser) {
      loadMessages();

      // 每3秒刷新一次訊息
      intervalRef.current = setInterval(() => {
        loadMessages(false); // false 表示靜默載入，不顯示載入動畫
        loadUnreadCounts(); // 同時更新未讀數量
      }, 3000);
    }

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
      }
    };
  }, [selectedUser]);

  // 自動滾動到底部
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const loadUsers = async () => {
    try {
      const response = await authAPI.getUsers();
      // 後端返回 ApiResponse 格式: { success, message, data }
      const usersData = response.data?.data || response.data || [];
      // 過濾掉當前用戶
      setUsers(Array.isArray(usersData) ? usersData.filter(u => u.id !== user.id) : []);
    } catch (error) {
      console.error('載入用戶列表失敗:', error);
      setUsers([]);
    }
  };

  // 載入所有用戶的未讀訊息數量
  const loadUnreadCounts = async () => {
    if (!user?.id) return;
    try {
      const response = await chatAPI.getUnreadMessages(user.id);

      // 解包 ApiResponse 格式
      const unreadMessages = response.data?.data || response.data || [];

      // 統計每個發送者的未讀訊息數量
      const counts = {};
      if (Array.isArray(unreadMessages)) {
        unreadMessages.forEach(msg => {
          if (msg.senderId && msg.senderId !== user.id) {
            counts[msg.senderId] = (counts[msg.senderId] || 0) + 1;
          }
        });
      }
      setUnreadCounts(counts);
    } catch (error) {
      console.error('載入未讀訊息數量失敗:', error);
    }
  };

  const loadMessages = async (showLoading = true) => {
    if (!selectedUser) return;

    if (showLoading) setLoading(true);

    try {
      const response = await chatAPI.getChatHistory(user.id, selectedUser.id);
      setMessages(response.data);

      // 標記為已讀
      await chatAPI.markChatAsRead(user.id, selectedUser.id);

      // 立即更新未讀數量
      await loadUnreadCounts();
    } catch (error) {
      console.error('載入訊息失敗:', error);
    } finally {
      if (showLoading) setLoading(false);
    }
  };

  const handleSelectUser = async (contact) => {
    setSelectedUser(contact);
    setMessages([]);
    // 標記與該用戶的對話為已讀
    try {
      await chatAPI.markChatAsRead(user.id, contact.id);
      // 重新載入未讀數量
      await loadUnreadCounts();
    } catch (error) {
      console.error('標記已讀失敗:', error);
    }
  };

  // 返回聯絡人列表 (手機版)
  const handleBackToContacts = () => {
    setSelectedUser(null);
  };

  const handleSendMessage = async (e) => {
    e.preventDefault();

    if (!newMessage.trim() || !selectedUser) return;

    try {
      await chatAPI.sendMessage({
        senderId: user.id,
        receiverId: selectedUser.id,
        message: newMessage.trim(),
      });

      setNewMessage('');
      await loadMessages(false);
      await loadUnreadCounts(); // 更新未讀數量
    } catch (error) {
      console.error('發送訊息失敗:', error);
      toast.error('發送失敗，請稍後再試');
    }
  };

  const formatTime = (timestamp) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('zh-TW', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <>
      <style>{`
        body { overflow: hidden; }
        .MuiAppBar-root { display: none !important; }
        .css-1b2brrz { padding: 0 !important; margin: 0 !important; }
        .MuiContainer-root { padding: 0 !important; margin: 0 !important; max-width: none !important; }
      `}</style>
      <div className="chat-container" style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1300,
        margin: 0,
        borderRadius: 0
      }}>
        {/* 側邊欄 */}
        <div style={{ top: 0 }} className={`sidebar ${isMobile && selectedUser ? 'mobile-hidden' : ''}`}>
          <div className="sidebar-header">
            <div className="user-info">
              <div className="user-avatar">{user?.name?.charAt(0) || user?.username?.charAt(0) || '?'}</div>
              <div>
                <div className="user-name">{user?.name || user?.username || '用戶'}</div>
                <div className="user-username">@{user?.username || ''}</div>
              </div>
            </div>
            <div className="header-buttons">
              <button className="btn-shop" onClick={() => navigate('/shop')}>
                🛍️ 商城
              </button>
              <button className="btn-logout" onClick={handleLogout}>
                登出
              </button>
            </div>
          </div>

          <div className="contacts-list">
            <h3>聯絡人</h3>
            {users.length === 0 ? (
              <div className="empty-contacts">沒有聯絡人</div>
            ) : (
              users.map((contact) => (
                <div
                  key={contact.id}
                  className={`contact-item ${selectedUser?.id === contact.id ? 'active' : ''}`}
                  onClick={() => handleSelectUser(contact)}
                >
                  <div className="contact-avatar">
                    {contact?.name?.charAt(0) || contact?.username?.charAt(0) || '?'}
                  </div>
                  <div className="contact-info">
                    <div className="contact-name">{contact?.name || contact?.username || '未知用戶'}</div>
                    <div className="contact-username">@{contact?.username || ''}</div>
                  </div>
                  {unreadCounts[contact.id] > 0 && (
                    <div className="unread-badge" title={`${unreadCounts[contact.id]} 則未讀訊息`}>
                      {unreadCounts[contact.id]}
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>

        {/* 聊天區域 */}
        <div className="chat-area">
          {selectedUser ? (
            <>
              <div className="chat-header">
                {isMobile && (
                  <button className="back-button" onClick={handleBackToContacts} title="返回聯絡人列表">
                    ←
                  </button>
                )}
                <div className="chat-avatar">
                  {selectedUser?.name?.charAt(0) || selectedUser?.username?.charAt(0) || '?'}
                </div>
                <div className="chat-info">
                  <h3>{selectedUser?.name || selectedUser?.username || '未知用戶'}</h3>
                  <p>@{selectedUser?.username || ''}</p>
                </div>
              </div>

              <div className="messages-container">
                {loading && messages.length === 0 ? (
                  <div className="loading">載入中...</div>
                ) : messages.length === 0 ? (
                  <div className="empty-state">
                    <div className="empty-icon">💬</div>
                    <p>還沒有訊息，開始聊天吧！</p>
                  </div>
                ) : (
                  <>
                    {messages.map((msg) => (
                      <div
                        key={msg.id}
                        className={`message ${msg.senderId === user.id ? 'sent' : 'received'}`}
                      >
                        <div className="message-content">
                          <div className="message-text">{msg.message}</div>
                          <div className="message-footer">
                            <span className="message-time">{formatTime(msg.timestamp)}</span>
                            {msg.senderId === user.id && (
                              <span className={`read-status ${msg.isRead ? 'read' : 'unread'}`}>
                                {msg.isRead ? '已讀' : '未讀'}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                    <div ref={messagesEndRef} />
                  </>
                )}
              </div>

              <form className="input-area" onSubmit={handleSendMessage}>
                <input
                  type="text"
                  value={newMessage}
                  onChange={(e) => setNewMessage(e.target.value)}
                  placeholder="輸入訊息..."
                  disabled={loading}
                />
                <button type="submit" disabled={!newMessage.trim() || loading}>
                  發送
                </button>
              </form>
            </>
          ) : (
            <div className="empty-chat">
              <div className="empty-icon">💬</div>
              <h3>{isMobile ? '開始聊天' : '選擇一個聯絡人'}</h3>
              <p>{isMobile ? '從左側選單選擇聯絡人開始對話' : '從左側選擇一個聯絡人開始聊天'}</p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}

export default Chat;
