// frontend/src/pages/Checkout.vue
<template>
  <v-container class="py-6" style="max-width: 900px">
    <v-btn variant="text" prepend-icon="mdi-arrow-left" to="/shop" class="mb-6">返回商城</v-btn>

    <!-- 載入中 -->
    <div v-if="loading" class="d-flex justify-center py-12">
      <v-progress-circular indeterminate color="primary" size="48" />
    </div>

    <v-row v-else>
      <!-- 收貨資訊表單 -->
      <v-col cols="12" md="6">
        <h1 class="text-h4 font-weight-bold mb-6">結帳</h1>
        <v-card>
          <v-card-title>收貨信息</v-card-title>
          <v-card-text>
            <v-form @submit.prevent="handleSubmit">
              <v-textarea
                v-model="formData.shippingAddress"
                label="收貨地址 *"
                variant="outlined"
                rows="3"
                required
                placeholder="請輸入詳細地址"
                class="mb-3"
              />
              <v-text-field
                v-model="formData.phone"
                label="聯絡電話 *"
                type="tel"
                variant="outlined"
                required
                placeholder="請輸入手機號碼 (09xxxxxxxx)"
                class="mb-3"
              />
              <v-textarea
                v-model="formData.note"
                label="訂單備註"
                variant="outlined"
                rows="2"
                placeholder="有什麼需要告訴我們的嗎？"
                class="mb-4"
              />
              <div class="d-flex gap-3">
                <v-btn variant="outlined" to="/shop" class="flex-grow-1">取消</v-btn>
                <v-btn
                  type="submit"
                  color="primary"
                  class="flex-grow-1"
                  :loading="submitting"
                  prepend-icon="mdi-credit-card"
                >
                  確認訂單
                </v-btn>
              </div>
            </v-form>
          </v-card-text>
        </v-card>
      </v-col>

      <!-- 訂單摘要 -->
      <v-col cols="12" md="6">
        <h2 class="text-h5 mb-4">訂單摘要</h2>
        <v-card>
          <v-list density="compact">
            <v-list-item
              v-for="item in cartItems"
              :key="item.id"
              :title="`${item.productName || item.product?.name} x${item.quantity}`"
              :subtitle="`$${parseFloat(item.subtotal || (item.price * item.quantity) || 0).toFixed(0)}`"
            />
          </v-list>
          <v-divider />
          <v-card-text>
            <div class="d-flex justify-space-between mb-1">
              <span>商品小計</span>
              <span>${{ parseFloat(total).toFixed(0) }}</span>
            </div>
            <div class="d-flex justify-space-between mb-1">
              <span>運費</span>
              <span>$60</span>
            </div>
            <v-divider class="my-2" />
            <div class="d-flex justify-space-between text-body-1 font-weight-bold">
              <span>總計</span>
              <span class="text-primary">${{ (parseFloat(total) + 60).toFixed(0) }}</span>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { orderAPI, cartAPI } from '../services/api.js'
import { useAuthStore } from '../stores/authStore.js'
import { cartEvents } from '../utils/cartEvents.js'

const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()
const user = computed(() => authStore.user)

const cart = ref(null)
const cartItems = ref([])
const loading = ref(true)
const submitting = ref(false)
const formData = ref({
  shippingAddress: '',
  phone: '',
  note: '',
})

const total = computed(() =>
  cart.value?.total ||
  cartItems.value.reduce((sum, item) => sum + parseFloat(item.subtotal || item.price * item.quantity || 0), 0)
)

async function loadCart() {
  if (!user.value?.id) return
  try {
    const response = await cartAPI.getCart(user.value.id)
    const cartData = response.data?.data || response.data
    cart.value = cartData
    cartItems.value = cartData?.items || []
    if (!cartData?.items || cartData.items.length === 0) {
      toast.error('購物車是空的！')
      router.push('/shop')
    }
    loading.value = false
  } catch {
    toast.error('載入購物車失敗')
    loading.value = false
  }
}

async function handleSubmit() {
  if (!formData.value.shippingAddress.trim()) {
    toast.error('請填寫收貨地址！')
    return
  }
  if (!formData.value.phone.trim()) {
    toast.error('請填寫聯絡電話！')
    return
  }
  const phoneRegex = /^09\d{8}$/
  if (!phoneRegex.test(formData.value.phone)) {
    toast.error('請輸入正確的台灣手機號碼格式 (例如: 0912345678)')
    return
  }

  submitting.value = true
  try {
    const params = new URLSearchParams({
      userId: user.value.id.toString(),
      shippingAddress: formData.value.shippingAddress,
      phone: formData.value.phone,
    })
    if (formData.value.note) params.append('note', formData.value.note)

    const response = await orderAPI.createOrder(`?${params.toString()}`)
    const orderData = response.data?.data || response.data

    try {
      await cartAPI.clearCart(user.value.id)
      cartEvents.notify()
    } catch {}

    toast.success('訂單建立成功！訂單編號: ' + (orderData.orderNumber || orderData.id))
    router.push('/orders')
  } catch (err) {
    toast.error(err.response?.data?.error || '建立訂單失敗')
    submitting.value = false
  }
}

onMounted(() => {
  if (!user.value?.id) {
    toast.error('請先登入')
    router.push('/login')
    return
  }
  formData.value.phone = user.value.phone || ''
  loadCart()
})
</script>

// frontend/src/pages/Checkout.jsx
﻿import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { orderAPI, cartAPI } from '../services/api';
import { useAuthStore } from '../stores/authStore';
import { cartEvents } from '../utils/cartEvents';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardTitle, CardHeader } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { ArrowLeft, Loader2, CreditCard } from 'lucide-react';

function Checkout() {
  const { user } = useAuthStore();
  const navigate = useNavigate();
  const [cart, setCart] = useState(null);
  const [cartItems, setCartItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    shippingAddress: '',
    phone: user?.phone || '',
    note: ''
  });

  useEffect(() => {
    if (!user?.id) {
      toast.error('請先登入');
      navigate('/login');
      return;
    }
    loadCart();
  }, []);

  const loadCart = async () => {
    if (!user?.id) return;

    try {
      const response = await cartAPI.getCart(user.id);
      const cartData = response.data?.data || response.data;
      setCart(cartData);
      setCartItems(cartData?.items || []);

      if (!cartData?.items || cartData.items.length === 0) {
        toast.error('購物車是空的!');
        navigate('/shop');
      }

      setLoading(false);
    } catch (error) {
      console.error('載入購物車失敗:', error);
      toast.error('載入購物車失敗');
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.shippingAddress.trim()) {
      toast.error('請填寫收貨地址!');
      return;
    }

    if (!formData.phone.trim()) {
      toast.error('請填寫聯絡電話!');
      return;
    }

    // 驗證台灣手機號碼格式
    const phoneRegex = /^09\d{8}$/;
    if (!phoneRegex.test(formData.phone)) {
      toast.error('請輸入正確的台灣手機號碼格式 (例如: 0912345678)');
      return;
    }

    if (!user?.id) {
      toast.error('請先登入');
      navigate('/login');
      return;
    }

    setSubmitting(true);

    try {
      // 使用查詢參數格式傳送資料
      const params = new URLSearchParams({
        userId: user.id.toString(),
        shippingAddress: formData.shippingAddress,
        phone: formData.phone,
      });

      if (formData.note) {
        params.append('note', formData.note);
      }

      const response = await orderAPI.createOrder(`?${params.toString()}`);
      const orderData = response.data?.data || response.data;

      // 清空購物車
      try {
        await cartAPI.clearCart(user.id);
        cartEvents.notify(); // 通知其他組件更新
      } catch (clearError) {
        console.error('清空購物車失敗:', clearError);
      }

      toast.success('訂單建立成功! 訂單編號: ' + (orderData.orderNumber || orderData.id));
      navigate('/orders');
    } catch (error) {
      console.error('建立訂單失敗:', error);
      toast.error(error.response?.data?.error || '建立訂單失敗');
      setSubmitting(false);
    }
  };

  if (loading) {
     return (
       <div className='container mx-auto py-8 text-center flex justify-center'>
         <Loader2 className='h-8 w-8 animate-spin' />
       </div>
     );
  }

  const total = cart?.total || cartItems.reduce((sum, item) => {
    const itemTotal = item.subtotal || (parseFloat(item.price || 0) * (item.quantity || 0));
    return sum + itemTotal;
  }, 0);

  return (
    <div className='container mx-auto py-8 px-4 max-w-4xl'>
      <Button
        variant='ghost'
        onClick={() => navigate('/shop')}
        className='mb-6 pl-0 hover:pl-2 transition-all'
      >
        <ArrowLeft className='mr-2 h-4 w-4' /> 返回商城
      </Button>

      <div className='grid gap-8 md:grid-cols-2'>
        <div>
          <h1 className='text-3xl font-bold mb-6'>結帳</h1>
          
          <Card>
            <CardHeader>
              <CardTitle>收貨信息</CardTitle>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className='space-y-6'>
                <div className='space-y-2'>
                  <Label htmlFor='shippingAddress'>收貨地址 *</Label>
                  <Textarea
                    id='shippingAddress'
                    name='shippingAddress'
                    value={formData.shippingAddress}
                    onChange={handleInputChange}
                    placeholder='請輸入詳細地址'
                    required
                  />
                </div>

                <div className='space-y-2'>
                  <Label htmlFor='phone'>聯絡電話 *</Label>
                  <Input
                    id='phone'
                    type='tel'
                    name='phone'
                    value={formData.phone}
                    onChange={handleInputChange}
                    placeholder='請輸入手機號碼 (09xxxxxxxx)'
                    required
                  />
                </div>

                <div className='space-y-2'>
                  <Label htmlFor='note'>訂單備註</Label>
                  <Textarea
                    id='note'
                    name='note'
                    value={formData.note}
                    onChange={handleInputChange}
                    placeholder='有什麼需要告訴我們的嗎?'
                  />
                </div>

                <div className='flex gap-4 pt-4'>
                  <Button
                    type='button'
                    variant='outline'
                    onClick={() => navigate('/shop')}
                    className='flex-1'
                    disabled={submitting}
                  >
                    取消
                  </Button>
                  <Button
                    type='submit'
                    className='flex-1'
                    disabled={submitting}
                  >
                    {submitting ? (
                        <>
                            <Loader2 className='mr-2 h-4 w-4 animate-spin' /> 處理中...
                        </>
                    ) : (
                        `確認結帳 ($${total.toFixed(0)})`
                    )}
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>

        <div>
          <Card className='sticky top-6'>
            <CardHeader>
              <CardTitle>訂單摘要</CardTitle>
            </CardHeader>
            <CardContent className='space-y-4'>
              <div className='space-y-3'>
                {cartItems.map((item) => (
                  <div key={item.id} className='flex justify-between items-start text-sm'>
                    <div>
                      <span className='font-medium block'>
                        {item.productName || item.product?.name || '商品'}
                      </span>
                      <span className='text-muted-foreground text-xs'>
                           {item.quantity}
                      </span>
                    </div>
                    <span className='font-medium'>
                      
                    </span>
                  </div>
                ))}
              </div>

               <hr className='my-4 border-gray-200' />

               <div className='flex justify-between text-lg font-bold'>
                 <span>總計</span>
                 <span className='text-primary'></span>
               </div>
               
               <div className='bg-muted p-4 rounded-lg mt-4 text-sm text-muted-foreground'>
                   <div className='flex items-center mb-2'>
                       <CreditCard className='h-4 w-4 mr-2' />
                       <span className='font-medium'>付款方式</span>
                   </div>
                   <p>目前僅支援貨到付款</p>
               </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

export default Checkout;
