// frontend/src/pages/Register.vue
<template>
  <v-app>
    <v-main class="bg-grey-lighten-3">
      <v-container class="fill-height" fluid>
        <v-row align="center" justify="center">
          <v-col cols="12" sm="8" md="5" lg="4">
            <v-card elevation="4" rounded="lg">
              <v-card-title class="text-h5 text-center pt-6 pb-2">
                📝 建立帳號
              </v-card-title>

              <v-card-text>
                <v-alert v-if="error" type="error" variant="tonal" class="mb-4" closable @click:close="error = ''">
                  {{ error }}
                </v-alert>

                <v-form @submit.prevent="handleSubmit">
                  <v-row>
                    <v-col cols="6">
                      <v-text-field
                        v-model="form.firstName"
                        label="名字"
                        variant="outlined"
                        density="compact"
                      />
                    </v-col>
                    <v-col cols="6">
                      <v-text-field
                        v-model="form.lastName"
                        label="姓氏"
                        variant="outlined"
                        density="compact"
                      />
                    </v-col>
                  </v-row>

                  <v-text-field
                    v-model="form.username"
                    label="帳號 *"
                    prepend-inner-icon="mdi-account"
                    variant="outlined"
                    class="mb-2"
                    required
                  />
                  <v-text-field
                    v-model="form.email"
                    label="電子郵件 *"
                    prepend-inner-icon="mdi-email"
                    type="email"
                    variant="outlined"
                    class="mb-2"
                    required
                  />
                  <v-text-field
                    v-model="form.password"
                    label="密碼 *"
                    prepend-inner-icon="mdi-lock"
                    :type="showPassword ? 'text' : 'password'"
                    :append-inner-icon="showPassword ? 'mdi-eye-off' : 'mdi-eye'"
                    @click:append-inner="showPassword = !showPassword"
                    variant="outlined"
                    class="mb-2"
                    required
                    hint="至少 6 個字符"
                  />
                  <v-text-field
                    v-model="form.confirmPassword"
                    label="確認密碼 *"
                    prepend-inner-icon="mdi-lock-check"
                    :type="showPassword ? 'text' : 'password'"
                    variant="outlined"
                    class="mb-4"
                    required
                  />

                  <v-btn
                    type="submit"
                    color="primary"
                    block
                    size="large"
                    :loading="loading"
                  >
                    建立帳號
                  </v-btn>
                </v-form>
              </v-card-text>

              <v-card-actions class="justify-center pb-4">
                <span class="text-body-2">已有帳號？</span>
                <RouterLink to="/login" class="text-primary text-body-2 ml-1">立即登入</RouterLink>
              </v-card-actions>
            </v-card>
          </v-col>
        </v-row>
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup>
import { ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { useAuthStore } from '../stores/authStore.js'
import { authAPI } from '../services/api.js'

const router = useRouter()
const toast = useToast()
const authStore = useAuthStore()

const form = ref({
  username: '',
  password: '',
  confirmPassword: '',
  firstName: '',
  lastName: '',
  email: '',
})
const error = ref('')
const loading = ref(false)
const showPassword = ref(false)

async function handleSubmit() {
  error.value = ''

  if (form.value.password !== form.value.confirmPassword) {
    error.value = '兩次輸入的密碼不一致'
    return
  }
  if (form.value.password.length < 6) {
    error.value = '密碼長度至少 6 個字符'
    return
  }

  loading.value = true
  try {
    const { confirmPassword, ...registerData } = form.value
    await authAPI.register(registerData)
    toast.success('註冊成功！正在為您登入...')

    const loginResponse = await authAPI.login({
      username: form.value.username,
      password: form.value.password,
    })
    const { token, user } = loginResponse.data.data
    authStore.login(user, token)
    router.push('/shop')
  } catch (err) {
    error.value = err.response?.data?.message || err.response?.data?.error || '註冊失敗，請稍後再試'
  } finally {
    loading.value = false
  }
}
</script>

// frontend/src/pages/Register.jsx
﻿import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAuthStore } from '../stores/authStore';
import { authAPI } from '../services/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import '../styles/Auth.css';

function Register() {
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    confirmPassword: '',
    firstName: '',
    lastName: '',
    email: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { login } = useAuthStore();

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    // 驗證密碼
    if (formData.password !== formData.confirmPassword) {
      setError('兩次輸入的密碼不一致');
      return;
    }

    if (formData.password.length < 6) {
      setError('密碼長度至少6個字符');
      return;
    }

    setLoading(true);

    try {
      const { confirmPassword, ...registerData } = formData;
      await authAPI.register(registerData);

      toast.success('註冊成功！正在為您登入...');

      // 註冊成功後自動登入
      const loginResponse = await authAPI.login({
        username: formData.username,
        password: formData.password,
      });

      // 後端返回格式: { success: true, data: { token: "...", user: {...} } }
      const { token, user } = loginResponse.data.data;
      login(user, token);
      navigate('/shop');
    } catch (err) {
      const errorMessage = err.response?.data?.message || err.response?.data?.error || '註冊失敗，請稍後再試';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto flex items-center justify-center min-h-[80vh] px-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <CardTitle className="text-2xl font-bold"> 現代電商</CardTitle>
          <p className="text-sm text-muted-foreground">建立新帳號</p>
        </CardHeader>
        <CardContent>
          {error && (
            <Alert variant="destructive" className="mb-4">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">用戶名</Label>
              <Input
                id="username"
                name="username"
                type="text"
                placeholder="請輸入用戶名"
                required
                value={formData.username}
                onChange={handleChange}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="email">電子郵件</Label>
              <Input
                id="email"
                name="email"
                type="email"
                placeholder="請輸入電子郵件"
                required
                value={formData.email}
                onChange={handleChange}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="firstName">名字</Label>
                <Input
                  id="firstName"
                  name="firstName"
                  type="text"
                  placeholder="名字"
                  value={formData.firstName}
                  onChange={handleChange}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="lastName">姓氏</Label>
                <Input
                  id="lastName"
                  name="lastName"
                  type="text"
                  placeholder="姓氏"
                  value={formData.lastName}
                  onChange={handleChange}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">密碼</Label>
              <Input
                id="password"
                name="password"
                type="password"
                placeholder="至少6個字符"
                required
                value={formData.password}
                onChange={handleChange}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirmPassword">確認密碼</Label>
              <Input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                placeholder="再次輸入密碼"
                required
                value={formData.confirmPassword}
                onChange={handleChange}
              />
            </div>

            <Button className="w-full" type="submit" disabled={loading}>
              {loading ? '註冊中...' : '註冊'}
            </Button>
          </form>
        </CardContent>
        <CardFooter className="flex justify-center">
          <div className="text-sm text-muted-foreground">
            已經有帳號?{" "}
            <Link to="/login" className="text-primary hover:underline">
              立即登入
            </Link>
          </div>
        </CardFooter>
      </Card>
    </div>
  );
}

export default Register;
