// frontend/src/pages/admin/Dashboard.vue
<template>
  <v-container class="py-6" style="max-width: 1200px">
    <h1 class="text-h4 font-weight-bold mb-6">管理員儀表板</h1>

    <v-row>
      <v-col v-for="stat in stats" :key="stat.title" cols="12" sm="6" md="3">
        <v-card height="100%">
          <v-card-text>
            <div class="d-flex align-center">
              <v-avatar :color="stat.color" class="mr-4">
                <v-icon :icon="stat.icon" color="white" />
              </v-avatar>
              <div>
                <p class="text-h4 font-weight-bold mb-0">{{ stat.display }}</p>
                <p class="text-body-2 text-medium-emphasis mb-0">{{ stat.title }}</p>
              </div>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
const stats = [
  { title: '總用戶數', display: '1,234', icon: 'mdi-account-group', color: 'primary' },
  { title: '總訂單數', display: '567', icon: 'mdi-shopping', color: 'success' },
  { title: '商品數量', display: '89', icon: 'mdi-trending-up', color: 'warning' },
  { title: '總收入', display: 'NT$ 123,456', icon: 'mdi-currency-usd', color: 'error' },
]
</script>

// frontend/src/pages/admin/Dashboard.jsx
import React from 'react';
import {
  Container,
  Typography,
  Grid,
  Card,
  CardContent,
  Box,
  Avatar
} from '@mui/material';
import {
  TrendingUp,
  People,
  ShoppingBag,
  AttachMoney
} from '@mui/icons-material';

export default function AdminDashboard() {
  // 這裡應該從 API 獲取真實數據
  const stats = {
    totalUsers: 1234,
    totalOrders: 567,
    totalProducts: 89,
    totalRevenue: 123456,
  };

  const StatCard = ({ title, value, icon, color }) => (
    <Card sx={{ height: '100%' }}>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center' }}>
          <Avatar sx={{ bgcolor: color, mr: 2 }}>
            {icon}
          </Avatar>
          <Box>
            <Typography variant="h4" component="div">
              {value}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {title}
            </Typography>
          </Box>
        </Box>
      </CardContent>
    </Card>
  );

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Typography variant="h4" gutterBottom>
        管理員儀表板
      </Typography>

      <Grid container spacing={3}>
        <Grid item xs={12} sm={6} md={3}>
          <StatCard
            title="總用戶數"
            value={stats.totalUsers}
            icon={<People />}
            color="primary.main"
          />
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <StatCard
            title="總訂單數"
            value={stats.totalOrders}
            icon={<ShoppingBag />}
            color="success.main"
          />
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <StatCard
            title="商品數量"
            value={stats.totalProducts}
            icon={<TrendingUp />}
            color="warning.main"
          />
        </Grid>

        <Grid item xs={12} sm={6} md={3}>
          <StatCard
            title="總收入"
            value={`NT$ ${stats.totalRevenue.toLocaleString()}`}
            icon={<AttachMoney />}
            color="error.main"
          />
        </Grid>
      </Grid>
    </Container>
  );
}
